// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/gorilla/mux"
	"go-labs-sql/api/handlers"
	"go-labs-sql/api/routes"
	"go-labs-sql/pkg/domain/repository"
	"go-labs-sql/pkg/infra"
)

// Injectors from wire.go:

func InitRouter() (*mux.Router, error) {
	router := routes.NewRouter()
	return router, nil
}

func InitUserRouter() (*routes.UserRouter, error) {
	db := infra.NewDatabaseConnection()
	postgresUserRepository := repository.NewPostgresUserRepository(db)
	userHandler := handlers.NewUserHandler(postgresUserRepository)
	userRouter := routes.NewUserRouter(userHandler)
	return userRouter, nil
}
